# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95d6f98c04f624fb964a975e6b1e611729d08f2b4e908026822975df42e2aa3c4e8d8766c4c8296fd4eaebcef18357da5a5326045365b620e84121741cdaf410

test:
  secret_key_base: dfd43e95e16d0499419c457fb90d9b66d84fa9090892baa70c42fba619de5191151561f369d4d3f14b87d8a3d06aec325704ac1493ebec7eec53ce20d17125f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
